### ISSUE TITLE
skills are not working in PromptTemplate (python-3.9)

### ISSUE THREAD

**Issue by joowon-dm-snu** [microsoft/semantic-kernel#182]
**Describe the bug**
After learning from the last issue that compatibility with 3.9 was not robust, 
I rerun the memory skill part and realized that it was not working properly.

This error is silent because `PromptTemplateEngine` is using `invoke_with_custom_iunput_async` function that contains try-exception code for rendering blocks.

originally it should show this error
```
DelegateHandlers.get_handler(self._delegate_type)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/joowonkim/Repo/semantic-kernel-jw/semantic-kernel/python/semantic_kernel/orchestration/delegate_handlers.py", line 155, in get_handler
    value.__wrapped__, "_delegate_type"
AttributeError: 'staticmethod' object has no attribute '__wrapped__'
```

similar with #168 `semantic-kernel/python/semantic_kernel/orchestration/delegate_handlers.py` needs change.

**To Reproduce**
run`semantic-kernel/python/tests/memory.py`
<img width="952" alt="image" src="https://user-images.githubusercontent.com/69464062/228143404-938af4f1-e782-40a7-a3f3-d6b12e4e3be3.png">

**Expected behavior**
`PromptTemplateEngine` render blocks correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/69464062/228135659-e480483a-5a1a-436e-a4f0-933e659df081.png)
![image](https://user-images.githubusercontent.com/69464062/228136602-272629c4-b374-412e-863e-a4d74ab31f96.png)

**Desktop (please complete the following information):**
 - OS: Mac M1
 - IDE: VS code
 - Python: 3.9.13

**Additional context**

**Comment by joowon-dm-snu** [comment]
while fixing this issue. i find out `staticmethod` is not callable in python3.9. need to handle it too.

![image](https://user-images.githubusercontent.com/69464062/228137934-b72ceaba-2e29-47c6-90ee-a35203610832.png)

**Comment by alexchaomander** [comment]
Thank you for finding these issues across the different Python versions!

**Comment by jjhenkel** [comment]
Agreed! We may want to decide sooner rather than later on a minimum supported version (which we should discuss) but, regardless, knowing a bit more about possible cross-version issues is a huge help so thank you @joowon-dm-snu !

**Comment by alexchaomander** [comment]
Merged!
