### PR TITLE
Python: Fix schema handling. Fix function result return for type list.

### LINKED ISSUE #6360: Python: Openai spec plugin with array type arguments is recognized as string during functional calling.
**Describe the bug**
Semantic kernel code:
```python
async def main():
    kernel = Kernel()
    service_id = "chat-gpt"

    service = AzureChatCompletion(
           ...
    )
    kernel.add_service(service)

    todo_plugin = await kernel.add_plugin_from_openai(
        plugin_name="TodoPlugin",
        plugin_url="http://localhost:3001/.well-known/ai-plugin.json",
    )
    print(todo_plugin.get_functions_metadata())
    settings = service.get_prompt_execution_settings_class()(service_id=service_id)
    settings.tool_choice = "auto"
    settings.function_call_behavior = FunctionCallBehavior.AutoInvokeKernelFunctions()
    arguments = KernelArguments(settings=settings)

    chat_history = ChatHistory()
    chat_history.add_user_message_str("What is the todo of id 1 and 2?")
    response = await service.get_chat_message_contents(
        chat_history=chat_history, settings=settings, kernel=kernel, arguments=arguments
    )
    content = response[0]
    print(content)
```
OpenAPI Spec:
```yml
openapi: 3.1.0
info:
  title: FastAPI
  version: 0.1.0
servers:
- url: http://127.0.0.1:3001
paths:
  /getlist:
    post:
      summary: Get Todo List
      description: A function that returns multiple todos. This function accept an
        array of objects.
      operationId: get_todo_list_getlist_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoGetList'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    TodoGet:
      properties:
        id:
          type: string
          title: Id
          description: Id of one todo content.
      type: object
      required:
      - id
      title: TodoGet
    TodoGetList:
      properties:
        ids:
          items:
            $ref: '#/components/schemas/TodoGet'
          type: array
          title: Ids
          description: Array of todo ids.
      type: object
      required:
      - ids
      title: TodoGetList
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
```
The request to OpenAI:
```
{ ...'tool_choice': 'auto', 'tools': [{'type': 'function', 'function': {'name': 'TodoPlugin-get_todo_list_getlist_post', 'description': 'Get Todo List', 'parameters': {'type': 'object', 'properties': {'ids': {'description': 'Array of todo ids.', 'type': 'string'}}, 'required': ['ids']}}}], 'top_p': 1.0}}
```
which this part I think is not correct (Not type string but type array and followed by inner parameter):
```
{'ids': {'description': 'Array of todo ids.', 'type': 'string'}}
```
And the final request body to the Openai plugin became:
```
{"ids": "1,2"}
```
instead of 
```
{
  "ids": [
    {
      "id": "1",
      "id": "2"
    }
  ]
}
```

**Platform**
 - Language: Python
 - Source: 1.0.0rc1

**Additional context**
The semantic kernel code above only works in version `1.0.0rc1`, does not work in version `1.0.0`.
In version `1.0.0`, an exception occurred, which may caused by an other bug:
```
  File "/.../python3.11/site-packages/semantic_kernel/connectors/ai/open_ai/services/utils.py", line 40, in parse_schema
    if schema_data.get("type") == "object":
       ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
```

### LINKED ISSUE #6367: Python: Kernel functions cannot handle list parameters.
**Describe the bug**
I am writing a native Python plugin. Stuff breaks if I use `list[str]` as parameters for my kernel_function.

**To Reproduce**
Define this kernel function:
```python
class AllergyPlugin:
    @kernel_function(
        name="FindAllergens",
        description="Filters a list of ingredients to find allergens."
    )
    def get_configuration(
        self,
        ingredients: Annotated[list[str], "The list of ingredients."]
    ) -> Annotated[list[str], "The list or allergens."]:
        return [ingredient for ingredient in ingredients if ingredient in ["peanuts"]]
```

My app starts up fine. Then when I ask `"What of the following ingredients are allergens? milk, soy, salt, peanuts, strawberries, and eggs"` I get the following error:
```
  File "/gen-ai/.venv/lib/python3.11/site-packages/semantic_kernel/functions/kernel_function_from_prompt.py", line 168, in _invoke_internal
    raise FunctionExecutionException(f"Error occurred while invoking function {self.name}: {exc}") from exc
semantic_kernel.exceptions.function_exceptions.FunctionExecutionException: Error occurred while invoking function Chat: ("<class 'semantic_kernel.connectors.ai.open_ai.services.azure_chat_completion.AzureChatCompletion'> service failed to complete the prompt", BadRequestError('Error code: 400 - {\'error\': {\'message\': "Invalid schema for function \'allergy-FindAllergens\': In context=(\'properties\', \'ingredients\'), array schema missing items", \'type\': \'invalid_request_error\', \'param\': None, \'code\': None}}'))
```

I have a workaround where I tell the agent to give me a string with a separator:
```python
class AllergyPlugin:
    @kernel_function(
        name="FindAllergens",
        description="Filters a list of ingredients to find allergens."
    )
    def get_configuration(
        self,
        ingredients: Annotated[str, "The list of ingredients separated by commas. Example 'milk, soy, eggs'"]
    ) -> Annotated[list[str], "The list or allergens."]:
        allergens = ["peanuts"]
        return [ingredient for ingredient in ingredients.split(", ") if ingredient in allergens]
```

Then the agent correctly replies with:
```
Among the ingredients listed, peanuts are identified as allergens.
```

**Expected behavior**
I expect kernel functions to handle list parameters.

**Screenshots**
NA

**Platform**
 - OS: [Mac]
 - IDE: [PyCharm]
 - Language: [Python]
 - Source: [library version 1.0.0]

**Additional context**

### PR DESCRIPTION
**Pull request by moonbox3**
### Motivation and Context

Building the tools json payload from the kernel parameter metadata wasn't properly including an object of type `array`.

### Description

Correctly include the object type `array` so that the tool call doesn't return a bad request. Add unit tests.
- Closes #6367 
- Closes #6360
- Fixes the FunctionResult return for a type string -- if the FunctionResult is of type KernelContent then return the first element of the list, otherwise return the complete list.
- Fix the kernel function from method to include the proper type_object for the return parameter so that the schema can be created properly.
- Add retry logic for a sometimes flaky function calling stepwise planner integration test. 
- Add a check during function calling that makes sure the model is returning the proper number of arguments based on how many function arguments are required.

### Contribution Checklist

- [X] The code builds clean without any errors or warnings
- [X] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [X] All unit tests pass, and I have added new tests where possible
- [X] I didn't break anyone :smile:

### CODE REVIEW

**Review by eavanvalkenburg — APPROVED** [review]

**Comment by markwallace-microsoft** [comment]
<a href="https://github.com/microsoft/semantic-kernel/blob/ddaf546ad6e83a3b2c15942b9cd9318dfaf54d74/README.md">Py3.10 Test Coverage</a><details><summary>Python 3.10 Test Coverage Report • </summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td colspan="5"><b>semantic_kernel/connectors/ai/open_ai/services</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/microsoft/semantic-kernel/blob/ddaf546ad6e83a3b2c15942b9cd9318dfaf54d74/python/semantic_kernel/connectors/ai/open_ai/services/utils.py">utils.py</a></td><td>20</td><td>14</td><td>30%</td><td><a href="https://github.com/microsoft/semantic-kernel/blob/ddaf546ad6e83a3b2c15942b9cd9318dfaf54d74/python/semantic_kernel/connectors/ai/open_ai/services/utils.py#L20-L30">20&ndash;30</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/ddaf546ad6e83a3b2c15942b9cd9318dfaf54d74/python/semantic_kernel/connectors/ai/open_ai/services/utils.py#L38-L53">38&ndash;53</a></td></tr><tr><td><b>TOTAL</b></td><td><b>5963</b></td><td><b>863</b></td><td><b>86%</b></td><td>&nbsp;</td></tr></tbody></table></details>

## Python 3.10 Unit Test Overview
| Tests | Skipped | Failures | Errors | Time |
| ----- | ------- | -------- | -------- | ------------------ |
| 1369 | 1 :zzz: | 0 :x: | 0 :fire: | 16.279s :stopwatch: |

**Review by alliscode — APPROVED** [review]
