### ISSUE TITLE
Python: Native python plugins do not work on version 1.0.0rc1

### ISSUE THREAD

**Issue by q-stefanmuscalu** [microsoft/semantic-kernel#6349]
**Describe the bug**
I am defining a native Python plugin. On version `0.9.8b1` it works fine. On version `1.0.0rc1` it does not.

**To Reproduce**
Define a plugin like this
```python
class CreditScore:
    @kernel_function(
        name="CreditScore",
        description="Calculate the credit score for a person given the person's name."
    )
    def credit_score(self, person_name: Annotated[str, "the person's name"]) -> Annotated[int, "The credit score as an integer between 0 and 100"]:
        if "smith" in str(person_name).lower():
            return 76
        else:
            return 12

kernel = sk.Kernel()
kernel.add_plugin(CreditScore(), plugin_name="creditScore")
planner = FunctionCallingStepwisePlanner(service_id="chatbot")
planner.invoke(kernel, "What is the credit score of John Smith?")
```

I get the following:
`OpenAIChatCompletionBase._process_function_call() got an unexpected keyword argument 'result'`

debug info:
```text
{
    'method': 'post',
    'url': '/chat/completions',
    'headers': {'api-key': 'XXX'},
    'files': None,
    'json_data': {
        'messages': [
            {
                'role':
                'user',
                'content': 'Original request: What is the credit score of John Smith?\n\nYou are in the process of helping the user fulfill this request using the following plan:\nTo find out the credit score of John Smith, follow these steps:\n\n1. Use the `creditScore-CreditScore` function with the parameter `person_name` set to "John Smith" to calculate John Smith\'s credit score.\n2. Once the credit score is obtained, use the `UserInteraction-SendFinalAnswer` function with the parameter `answer` set to the credit score obtained in step 1 to communicate the credit score back to the user.\n\nThe user will ask you for help with each step.'
            },
            {
                'role': 'user',
                'content': 'Perform the next step of the plan if there is more work to do. When you have reached a final answer, use the UserInteraction-SendFinalAnswer function to communicate this back to the user.'
            },
            {
                'role': 'assistant',
                'tool_calls': [
                    {'id': 'call_lI0LrybtI4ui3Ew5hxbQMm9Q', 'type': 'function', 'function': {'name': 'creditScore-CreditScore', 'arguments': '{"person_name":"John Smith"}'}}
                ]
            },
            {
                'role': 'tool',
                'content': "An error occurred during planner invocation: OpenAIChatCompletionBase._process_function_call() got an unexpected keyword argument 'result'",
                'tool_call_id': 'call_lI0LrybtI4ui3Ew5hxbQMm9Q'
            },
            {
                'role': 'user',
                'content': 'Perform the next step of the plan if there is more work to do. When you have reached a final answer, use the UserInteraction-SendFinalAnswer function to communicate this back to the user.'
            }
        ],
        'model': 'XXX-gpt-4',
        'frequency_penalty': 0.0,
        'logit_bias': {},
        'max_tokens': 200,
        'n': 1,
        'presence_penalty': 0.0,
        'stream': False,
        'temperature': 0.0,
        'tool_choice': 'auto',
        'tools': [
            {'type': 'function', 'function': {'name': 'creditScore-CreditScore', 'description': "Calculate the credit score for a person given the person's name.", 'parameters': {'type': 'object', 'properties': {'person_name': {'description': "the person's name", 'type': 'string'}}, 'required': ['person_name']}}},
            {'type': 'function', 'function': {'name': 'UserInteraction-SendFinalAnswer', 'description': 'The final answer to return to the user', 'parameters': {'type': 'object', 'properties': {'answer': {'description': 'The final answer', 'type': 'string'}}, 'required': ['answer']}}},
            {'type': 'function', 'function': {'name': 'sequential_planner-create_plan', 'description': 'Create a plan for the given goal', 'parameters': {'type': 'object', 'properties': {'available_functions': {'description': 'A list of functions that can be used to generate the plan', 'type': 'string'}, 'goal': {'description': 'The goal to satisfy', 'type': 'string'}, 'name_delimiter': {'description': '', 'type': 'string'}}, 'required': ['available_functions', 'goal', 'name_delimiter']}}}
        ],
        'top_p': 1.0
    }
}
```

**Expected behavior**
I expect the response to be 76.

**Screenshots**
N/A

**Platform**
 - OS: [Mac]
 - IDE: [VS Code]
 - Language: [Python]
 - Source: [1.0.0rc1]

**Additional context**
N/A

**Comment by eavanvalkenburg** [comment]
This was fixed in 1.0.0, please try that.

**Comment by q-stefanmuscalu** [comment]
Hey, thank you for your reply. I upgraded to 1.0.0 and now I see the issue mentioned here https://github.com/microsoft/semantic-kernel/issues/6350

**Comment by q-stefanmuscalu** [comment]
It looks like the issue is in the planner. If instead of `planner.invoke(kernel, question)` I do `kernel.invoke(question)` then stuff works fine. I'll just do that. :)

**Comment by moonbox3** [comment]
> It looks like the issue is in the planner. If instead of `planner.invoke(kernel, question)` I do `kernel.invoke(question)` then stuff works fine. I'll just do that. :)

Thanks for the feedback @q-stefanmuscalu. We are still going to investigate this. When you encountered the issue in #6350, you're using AzureOpenAI, correct? Which AOAI API version are you targeting?

**Comment by moonbox3** [comment]
FYI @q-stefanmuscalu #6357 will fix the FC stepwise planner issue.

**Comment by moonbox3** [comment]
Fixed with #6357. Closing.
