### ISSUE TITLE
Python: Openai spec plugin with array type arguments is recognized as string during functional calling.

### ISSUE THREAD

**Issue by sbkkalex** [microsoft/semantic-kernel#6360]
**Describe the bug**
Semantic kernel code:
```python
async def main():
    kernel = Kernel()
    service_id = "chat-gpt"

    service = AzureChatCompletion(
           ...
    )
    kernel.add_service(service)

    todo_plugin = await kernel.add_plugin_from_openai(
        plugin_name="TodoPlugin",
        plugin_url="http://localhost:3001/.well-known/ai-plugin.json",
    )
    print(todo_plugin.get_functions_metadata())
    settings = service.get_prompt_execution_settings_class()(service_id=service_id)
    settings.tool_choice = "auto"
    settings.function_call_behavior = FunctionCallBehavior.AutoInvokeKernelFunctions()
    arguments = KernelArguments(settings=settings)

    chat_history = ChatHistory()
    chat_history.add_user_message_str("What is the todo of id 1 and 2?")
    response = await service.get_chat_message_contents(
        chat_history=chat_history, settings=settings, kernel=kernel, arguments=arguments
    )
    content = response[0]
    print(content)
```
OpenAPI Spec:
```yml
openapi: 3.1.0
info:
  title: FastAPI
  version: 0.1.0
servers:
- url: http://127.0.0.1:3001
paths:
  /getlist:
    post:
      summary: Get Todo List
      description: A function that returns multiple todos. This function accept an
        array of objects.
      operationId: get_todo_list_getlist_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TodoGetList'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    TodoGet:
      properties:
        id:
          type: string
          title: Id
          description: Id of one todo content.
      type: object
      required:
      - id
      title: TodoGet
    TodoGetList:
      properties:
        ids:
          items:
            $ref: '#/components/schemas/TodoGet'
          type: array
          title: Ids
          description: Array of todo ids.
      type: object
      required:
      - ids
      title: TodoGetList
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
```
The request to OpenAI:
```
{ ...'tool_choice': 'auto', 'tools': [{'type': 'function', 'function': {'name': 'TodoPlugin-get_todo_list_getlist_post', 'description': 'Get Todo List', 'parameters': {'type': 'object', 'properties': {'ids': {'description': 'Array of todo ids.', 'type': 'string'}}, 'required': ['ids']}}}], 'top_p': 1.0}}
```
which this part I think is not correct (Not type string but type array and followed by inner parameter):
```
{'ids': {'description': 'Array of todo ids.', 'type': 'string'}}
```
And the final request body to the Openai plugin became:
```
{"ids": "1,2"}
```
instead of 
```
{
  "ids": [
    {
      "id": "1",
      "id": "2"
    }
  ]
}
```

**Platform**
 - Language: Python
 - Source: 1.0.0rc1

**Additional context**
The semantic kernel code above only works in version `1.0.0rc1`, does not work in version `1.0.0`.
In version `1.0.0`, an exception occurred, which may caused by an other bug:
```
  File "/.../python3.11/site-packages/semantic_kernel/connectors/ai/open_ai/services/utils.py", line 40, in parse_schema
    if schema_data.get("type") == "object":
       ^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by moonbox3** [comment]
Thanks for filing, @sbkkalex. Let me have a look at this.
