### PR TITLE
Python: fix for fc stepwise

### LINKED ISSUE #6333: FunctionCallingStepwisePlanner not working in semantic-kernel 1.0.0rc1 | programming language python
**Describe the bug**
I have implemented to test FunctionCallingStepwisePlanner  but got below issue:
**An error occurred during planner invocation: OpenAIChatCompletionBase._process_function_call() got an unexpected keyword argument 'result'**

**To Reproduce**

**Expected behavior**
It should work.

**Screenshots**

**Platform**
 - OS: Windows
 - IDE: VS Code
 - Language: Python
 - Source: semantic-kernel 1.0.0rc1

**Additional context**
semantic_kernel\planners\function_calling_stepwise_planner\function_calling_stepwise_planner.py
	result param is not used in chat_completion._process_function_call method that need to fix

### PR DESCRIPTION
**Pull request by eavanvalkenburg**
### Motivation and Context

fixes #6333 

### Contribution Checklist

- [x] The code builds clean without any errors or warnings
- [x] The PR follows the [SK Contribution Guidelines](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md) and the [pre-submission formatting script](https://github.com/microsoft/semantic-kernel/blob/main/CONTRIBUTING.md#development-scripts) raises no violations
- [x] All unit tests pass, and I have added new tests where possible
- [x] I didn't break anyone :smile:

### CODE REVIEW

**Review by moonbox3 — APPROVED** [review]

**Comment by markwallace-microsoft** [comment]
<a href="https://github.com/microsoft/semantic-kernel/blob/ac2d397447c3698e465b14c97b4eb60a016ac978/README.md">Py3.10 Test Coverage</a><details><summary>Python 3.10 Test Coverage Report • </summary><table><tr><th>File</th><th>Stmts</th><th>Miss</th><th>Cover</th><th>Missing</th></tr><tbody><tr><td colspan="5"><b>semantic_kernel/connectors/ai/open_ai/services</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/microsoft/semantic-kernel/blob/ac2d397447c3698e465b14c97b4eb60a016ac978/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py">open_ai_chat_completion_base.py</a></td><td>211</td><td>93</td><td>56%</td><td><a href="https://github.com/microsoft/semantic-kernel/blob/ac2d397447c3698e465b14c97b4eb60a016ac978/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L97">97</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/ac2d397447c3698e465b14c97b4eb60a016ac978/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L117">117</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/ac2d397447c3698e465b14c97b4eb60a016ac978/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L142-L146">142&ndash;146</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/ac2d397447c3698e465b14c97b4eb60a016ac978/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L170">170</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/ac2d397447c3698e465b14c97b4eb60a016ac978/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L174">174</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/ac2d397447c3698e465b14c97b4eb60a016ac978/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L190-L195">190&ndash;195</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/ac2d397447c3698e465b14c97b4eb60a016ac978/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L212-L240">212&ndash;240</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/ac2d397447c3698e465b14c97b4eb60a016ac978/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L243-L254">243&ndash;254</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/ac2d397447c3698e465b14c97b4eb60a016ac978/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L272-L279">272&ndash;279</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/ac2d397447c3698e465b14c97b4eb60a016ac978/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L290-L298">290&ndash;298</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/ac2d397447c3698e465b14c97b4eb60a016ac978/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L314-L321">314&ndash;321</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/ac2d397447c3698e465b14c97b4eb60a016ac978/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L342">342</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/ac2d397447c3698e465b14c97b4eb60a016ac978/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L350">350</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/ac2d397447c3698e465b14c97b4eb60a016ac978/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L356-L362">356&ndash;362</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/ac2d397447c3698e465b14c97b4eb60a016ac978/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L374-L380">374&ndash;380</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/ac2d397447c3698e465b14c97b4eb60a016ac978/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L411">411</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/ac2d397447c3698e465b14c97b4eb60a016ac978/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L450">450</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/ac2d397447c3698e465b14c97b4eb60a016ac978/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L452-L453">452&ndash;453</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/ac2d397447c3698e465b14c97b4eb60a016ac978/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L458-L463">458&ndash;463</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/ac2d397447c3698e465b14c97b4eb60a016ac978/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L467-L474">467&ndash;474</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/ac2d397447c3698e465b14c97b4eb60a016ac978/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L496">496</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/ac2d397447c3698e465b14c97b4eb60a016ac978/python/semantic_kernel/connectors/ai/open_ai/services/open_ai_chat_completion_base.py#L505-L514">505&ndash;514</a></td></tr><tr><td colspan="5"><b>semantic_kernel/planners/function_calling_stepwise_planner</b></td></tr><tr><td>&nbsp; &nbsp;<a href="https://github.com/microsoft/semantic-kernel/blob/ac2d397447c3698e465b14c97b4eb60a016ac978/python/semantic_kernel/planners/function_calling_stepwise_planner/function_calling_stepwise_planner.py">function_calling_stepwise_planner.py</a></td><td>110</td><td>42</td><td>62%</td><td><a href="https://github.com/microsoft/semantic-kernel/blob/ac2d397447c3698e465b14c97b4eb60a016ac978/python/semantic_kernel/planners/function_calling_stepwise_planner/function_calling_stepwise_planner.py#L126-L213">126&ndash;213</a>, <a href="https://github.com/microsoft/semantic-kernel/blob/ac2d397447c3698e465b14c97b4eb60a016ac978/python/semantic_kernel/planners/function_calling_stepwise_planner/function_calling_stepwise_planner.py#L247-L252">247&ndash;252</a></td></tr><tr><td><b>TOTAL</b></td><td><b>6176</b></td><td><b>1036</b></td><td><b>83%</b></td><td>&nbsp;</td></tr></tbody></table></details>

## Python 3.10 Unit Test Overview
| Tests | Skipped | Failures | Errors | Time |
| ----- | ------- | -------- | -------- | ------------------ |
| 1328 | 1 :zzz: | 0 :x: | 0 :fire: | 12.858s :stopwatch: |

**Review by alliscode — APPROVED** [review]
