### ISSUE TITLE
FunctionCallingStepwisePlanner not working in semantic-kernel 1.0.0rc1 | programming language python

### ISSUE THREAD

**Issue by rvishwakarma001** [microsoft/semantic-kernel#6333]
**Describe the bug**
I have implemented to test FunctionCallingStepwisePlanner  but got below issue:
**An error occurred during planner invocation: OpenAIChatCompletionBase._process_function_call() got an unexpected keyword argument 'result'**

**To Reproduce**

**Expected behavior**
It should work.

**Screenshots**

**Platform**
 - OS: Windows
 - IDE: VS Code
 - Language: Python
 - Source: semantic-kernel 1.0.0rc1

**Additional context**
semantic_kernel\planners\function_calling_stepwise_planner\function_calling_stepwise_planner.py
	result param is not used in chat_completion._process_function_call method that need to fix

**Comment by cory-orennia** [comment]
Can confirm encountering the same issue.

**Comment by rvishwakarma001** [comment]
> Can confirm encountering the same issue.

Yes
